# Generated by Django 3.2.19 on 2023-06-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230610_1931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
