# Generated by Django 3.2.19 on 2023-06-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_testreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testreport',
            old_name='user',
            new_name='user_id',
        ),
    ]
