# Generated by Django 3.2.19 on 2023-06-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_user_testreport_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testreport',
            name='user_id',
        ),
        migrations.AddField(
            model_name='testreport',
            name='account_id',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
